# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eoUVXqrZP1Inm-Kc2FBgmEaExhErPPed
"""

import streamlit as st
st.title("Sentiment analysis")
st.text_input("Enter your text")
